// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface CropSearchModalStyle {
  'input': string;
}

export const useCropSearchModalStyle = useCssModule as unknown as (() => CropSearchModalStyle);