// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DiseasePagePesticidesStyle {
  'list': string;
  'red_color': string;
  'warning': string;
}

export const useDiseasePagePesticidesStyle = useCssModule as unknown as (() => DiseasePagePesticidesStyle);