// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DiseasePageMainStyle {
  'full_width': string;
  'root': string;
}

export const useDiseasePageMainStyle = useCssModule as unknown as (() => DiseasePageMainStyle);