// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DiseasePageDiagnosticStyle {
  'root': string;
}

export const useDiseasePageDiagnosticStyle = useCssModule as unknown as (() => DiseasePageDiagnosticStyle);