// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface ArticleWrapStyle {
  'apply_button': string;
  'full_height': string;
  'root': string;
  'wrap': string;
}

export const useArticleWrapStyle = useCssModule as unknown as (() => ArticleWrapStyle);