// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface ArticleConfusedSectionStyle {
  'icon': string;
  'image': string;
}

export const useArticleConfusedSectionStyle = useCssModule as unknown as (() => ArticleConfusedSectionStyle);