// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface ArticleSliderSectionStyle {
  'icon': string;
  'image': string;
}

export const useArticleSliderSectionStyle = useCssModule as unknown as (() => ArticleSliderSectionStyle);