// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DictArticleStyle {
  'apply_button': string;
  'content': string;
  'delimiter': string;
  'gallery': string;
  'gallery_container': string;
  'root': string;
}

export const useDictArticleStyle = useCssModule as unknown as (() => DictArticleStyle);