// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface EmptyScreenStyle {
  'description': string;
  'icon': string;
  'root': string;
  'title': string;
}

export const useEmptyScreenStyle = useCssModule as unknown as (() => EmptyScreenStyle);