// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface VSCropCardStyle {
  'culture_default': string;
  'icon': string;
  'item': string;
}

export const useVSCropCardStyle = useCssModule as unknown as (() => VSCropCardStyle);