// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface VSImageCardStyle {
  'icon': string;
}

export const useVSImageCardStyle = useCssModule as unknown as (() => VSImageCardStyle);