// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DictsHeaderStyle {
  'close': string;
  'icon': string;
  'icon_color': string;
  'icon_container': string;
  'name': string;
  'name_offset': string;
  'root': string;
  'search': string;
  'subtitle': string;
  'title': string;
}

export const useDictsHeaderStyle = useCssModule as unknown as (() => DictsHeaderStyle);