// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface SeedCropInitStyle {
  'cluster': string;
  'helper': string;
  'overlay': string;
  'root': string;
}

export const useSeedCropInitStyle = useCssModule as unknown as (() => SeedCropInitStyle);