// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface ConfusedDiseasesFieldStyle {
  'container': string;
  'root': string;
}

export const useConfusedDiseasesFieldStyle = useCssModule as unknown as (() => ConfusedDiseasesFieldStyle);