// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface CropPartSelectFieldsStyle {
  'root': string;
  'select': string;
}

export const useCropPartSelectFieldsStyle = useCssModule as unknown as (() => CropPartSelectFieldsStyle);