// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DamagesFieldStyle {
  'damage': string;
  'damages': string;
  'root': string;
}

export const useDamagesFieldStyle = useCssModule as unknown as (() => DamagesFieldStyle);