// This file is automatically generated.
// Please do not change this file!

import { useCssModule } from 'vue';

export interface DiagnosticMethodsFieldStyle {
  'method': string;
  'root': string;
}

export const useDiagnosticMethodsFieldStyle = useCssModule as unknown as (() => DiagnosticMethodsFieldStyle);